# Generated by Django 3.1 on 2021-01-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.CharField(max_length=300),
        ),
    ]
