# Generated by Django 3.1 on 2021-01-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0004_auto_20210114_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
