# Generated by Django 3.1 on 2021-01-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0005_image_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='source',
        ),
    ]
